version: "3.9"

services:
  node-js:
    image: node:18
    build: .
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development

networks:
  default:
    name: cnp2_net

